### ISSUE TITLE
error in npm run dev

### ISSUE THREAD

**Issue by sudeepdk** [iurii-kyrylenko/hobbies#3]
ERROR  Failed to compile with 3 errors                                                                                                4:39:20 PM

This dependency was not found:

* file-saver/fileSaver in ./src/store/modules/items.js

To install it, you can run: npm install --save file-saver/fileSaver

These relative modules were not found:

* ./components/navbar in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
* ./components/notifier in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue

**Comment by iurii-kyrylenko** [comment]
Thanks @sudeepdk,
I'll look into the issue.

**Comment by iurii-kyrylenko** [comment]
@sudeepdk,
1. Have you installed the `front-end-vue` successfully (`npm install`) ?
2. Do you have `FileSaver.js` in `/front-end-vue/node_modules/file-saver`?

**Comment by iurii-kyrylenko** [comment]
@sudeepdk,
Please check, if it is OK now.
Thank you.

**Comment by sudeepdk** [comment]
resolved ... thanks for quick fix .. @iurii-kyrylenko
