### ISSUE TITLE
ReCaptcha.vue config advice

### ISSUE THREAD

**Issue by teamhail** [iurii-kyrylenko/hobbies#7]
Hello and thank you for this project.  A quick question:  where do I set the site-key and the client-key for the reCaptcha?   

1. What should be set in for /hobbies-master/front-end-vue/src/helpers/config.js for "reCaptchaSiteKey"?
2. What should be set for production in the .env file for the "CAPTCHA_SECRET"?
3. What should be set in the .env file for "JWT_SECRET"?

Thanks again!

**Comment by iurii-kyrylenko** [comment]
Hi @teamhail,

- All info on reCAPTCHA you can find in [dev guide](https://developers.google.com/recaptcha/intro).
- The site key and the secret key you get at the [admin site](https://www.google.com/recaptcha/admin) after signing up.
- Use the site key in the `reCaptchaSiteKey` getter in the `helpers/config.js`.
- Set the secret key in .env file under the `CAPTCHA_SECRET`. Actually, I use the .env file only in development. For production I set the environment vars on the Heroku.
- For the `JWT_SECRET` chose any string you like.
